swagger: "2.0"
info:
  title: Title
  description: Title
  version: 1.0.0
host: www
schemes:
  - https
paths:
  /url:
    get:
      description: New endpoint
      responses:
        200:
          description: New response

